ami:
  - changed-files:
      - any-glob-to-any-file:
          - crates/asterisk-rs-ami/**

agi:
  - changed-files:
      - any-glob-to-any-file:
          - crates/asterisk-rs-agi/**

ari:
  - changed-files:
      - any-glob-to-any-file:
          - crates/asterisk-rs-ari/**

core:
  - changed-files:
      - any-glob-to-any-file:
          - crates/asterisk-rs-core/**

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**
          - "*.md"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - Cargo.toml
          - Cargo.lock
          - deny.toml
